name: "Central AI Brain"
version: "0.11.0"
slug: "central_ai_addon"
description: "A central AI service using Ollama to provide intelligence to Home Assistant."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: "auto"
init: false
options:
  ai_engine_url: "http://<IP_OF_AI_ENGINE>:8099/api/prompt"
  mqtt_host: "10.0.110.124"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
schema:
  ai_engine_url: "url"
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_user: "str"
  mqtt_password: "password"
api: true
homeassistant_api: true