name: "Switch as Light"
version: "0.1.0"
slug: "switch_as_light"
description: "Automatically create light entities from switches using MQTT Discovery."
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  ha_url: "http://supervisor/core"
  ha_token: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  log_level: "info"
schema:
  ha_url: "url"
  ha_token: "password"
  mqtt_host: "str"
  mqtt_port: "port"
  mqtt_user: "str?"
  mqtt_password: "password?"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
